<?php

/**
 * PluginPageSatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageSatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageSatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageSat');
    }

    public function retrieveBySlugAndCulture($slug, $culture = 'fr'){
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);

        $q->andWhere('a.slug = ?', $slug);

        return $q->fetchOne();
    }

    public function retrieveAllActive($culture = 'fr'){
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);

        return $q->execute();
    }

    public function retrieveAllActiveInMenu($culture = 'fr'){
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);

        $q->andWhere('a.in_menu = ?', 1);

        return $q->execute();
    }

    protected function addCultureQuery(Doctrine_Query $q = null, $culture)
    {
        if (is_null($q))
	    {
	      $q = Doctrine_Query::create()
	        ->from('PageSat p');
	    }

        $alias = $q->getRootAlias();

        $q->andWhere($alias.'.lang = ?', $culture);

        return $q;
    }

    protected function addActiveQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
	    {
	      $q = Doctrine_Query::create()
	        ->from('PageSat p');
	    }

        $alias = $q->getRootAlias();

        $q->andWhere($alias.'.enabled = ?', PageSat::ENABLED);

        return $q;
    }
}