<?php

/**
 * PluginKeywordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKeywordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginKeywordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginKeyword');
    }
}