<?php

/**
 * PluginPageRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageRedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageRedirect');
    }

    /**
     * @param $slug
     * @param null $host
     * @return PageRedirect object
     */
    public function retrieveOneBySlugandHost($slug, $host = null){
        $q = $this->createQuery('a')
                ->where('a.url = ?', $slug);

        if(!is_null($host)){
            $q->addWhere('a.host = ? ', $host);
        }

        return $q->fetchOne();
    }
}