<?php

/**
 * PluginPageRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageRedirectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageRedirect');
    }
}