<?php

/**
 * PluginPageSatAutoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageSatAutoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageSatAutoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageSatAuto');
    }


    public function retrieveAllActive()
    {
        $q = $this->createQuery('a')
            ->where('a.nb_results > ?', 0);

        return $q->execute();
    }

}