generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PageSat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pix_page_sat_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
        display: [enabled, =title, lang, updated_at]
        title: Liste des pages sat
      filter:  ~
      form:    ~
      edit:
        title: Editer la page sat "%%title%%"
      new:
        title: Ajouter une page sat
