all:
  pixSeo:
    routes_register: true
    multi_domain: false  # enable if multiple domains are used for the page sat
    default_host_prefix: false # define the prefix for the default host (www, dev, test ...)
    route_class: pixSeoRoute

    enabled_cultures:
      en:
        code: en
        label: English
      fr:
        code: fr
        label: français

    metas:
      default_title: # finish title with a dash
      default_description: # finish description with a dash
      default_keywords: # finish list with a comma

    analytics:
      www.example.com: 'UA-XXXXXXXX-X'

    cookie_name: your_cookie_name

    pageSatAuto:
      load_default: false # whether or not loading the default meta defined below
      meta_title: # use {keyword} as a placeholder to load dynamically the keyword in database
      meta_description:
      meta_keywords: