all:
  pixSeo:
    routes_register: true
    #default_host: false
    route_class: pixSeoRoute

    enabled_cultures:
      en:
        code: en
        label: English
      fr:
        code: fr
        label: français

    metas:
      default_title: # finish title with a dash
      default_description: # finish description with a dash
      default_keywords: # finish list with a comma

    analytics:
      www.example.com: 'UA-XXXXXXXX-X'